apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
  namespace: workshopctl
spec:
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - env:
        - name: GIT_REPO
          value: https://github.com/luxas/workshopctl
        - name: GIT_SUBDIR
          value: tutorials
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: VSCODE_PASSWORD
              name: workshopctl
        image: luxas/k8s-web-ide:v2.0.0
        imagePullPolicy: Always
        name: code-server
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: /home/coder/.kube
          name: kubeconfig
        - mountPath: /var/run/docker.sock
          name: docker
      serviceAccountName: code-server
      volumes:
      - configMap:
          name: code-server
        name: kubeconfig
      - hostPath:
          path: /var/run/docker.sock
        name: docker
